import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub
} from "react-icons/ai";
import reactLogo from "../public/reactLogo.png"
import JAVA from "../public/JAVA.png"
import nodejS from "../public/nodejS.png"
import css from "../public/css.png"
import tawinlind from "../public/tawinlind.png"
import mongoDb from "../public/mongoDb.png"
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/yassin.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "" : "dark"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">yassin-<span className=" text-teal-600">bouzgarrou 👋</span></h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text-to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="/bbbbb.pdf"
                  download="my-cv"
                >
                  Resume
                </a>

              </li>
            </ul>
          </nav>
          <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-40 md:w-40">
            <Image src={deved} layout="fill" objectFit="cover" />
          </div>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Med yassin bouzgarrou
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              full stack developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I am Yassin Bouzgarou, a highly motivated and dynamic full-stack developer with an insatiable thirst for knowledge and an unwavering commitment to excellence. Driven by my innate curiosity and an eagerness to learn,
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href='https://github.com/yassin-bouzgarrou'> <AiFillGithub /> </a>
              <a href="https://www.linkedin.com/in/yassin-bouzgarrou-227b48278/"><AiFillLinkedin /> </a>

            </div>

          </div>



        </section>
        <section>
          <div>
            <h3 className="text-4xl py-1  text-teal-600 ">Services I offer</h3>


          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600 font-bold">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">canva</p>
              <p className="text-gray-800 py-1">Figma</p>

            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Let's make it a
                reality.
              </p>
              <h4 className="py-4 text-teal-600 font-bold">technology i use</h4>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">Html</p>
              <p className="text-gray-800 py-1">Css</p>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Node Js</p>
              <p className="text-gray-800 py-1">Vue</p>
              <p className="text-gray-800 py-1">Mongodb</p>
              <p className="text-gray-800 py-1">Mysql</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>

            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-4xl py-1  text-teal-600 ">Portofolio</h3>
            <p className="text-xl py-2 leading-8 text-gray-800 dark:text-gray-200 min-w-[50%] w-[1050px]">
              I have worked on a range of projects, including a car and bike rental platform, a food delivery system, a mobile app,
              and an event booking app. For the rental platform, I developed user-friendly interfaces and implemented a secure booking system. In the food delivery system,
              I focused on creating a seamless ordering process and real-time tracking features. The mobile app project involved designing intuitive interfaces and integrating social
              media sharing capabilities. Lastly, I contributed to the development of an event booking app with a ticketing system. These projects have allowed me to enhance my skills
              in various areas of web and mobile development
            </p>

          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"160%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"160%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"160%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"160%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>


          </div>
        </section>
      </main>
    </div >
  );
}
